# You can access the intermediate code generated by every instruction in python3
# This example shows the performance difference between building a list and a tuple object

import dis 

print(dis.dis(compile("(1,2,3,4,5,6)", "", "eval")))


print(dis.dis(compile("[1,2,3,4,5,6]", "", "eval")))
